name: CICD Docker
on:
  push:
    branches:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run npm install
        run: npm install
      - name: Run unit test
        run: npm test
